### ISSUE TITLE
RMS: Customer Sharing

### ISSUE THREAD

**Issue by game7** [game7/sportified#103]
Customer information should be present in both application and client stripe accounts.  At one point we had this working but currently it is not.

**Comment by game7** [comment]
@leaguetek01 I've made some changes so that customer information is now visible in connected accounts (i.e. styfl).  After testing a variety of methods it would appear very difficult to maintain unique, non-redundant customer accounts in connected applications.  Rather, each new charge will create a new customer record so that there will be a 1:1 ratio between the two.  The downside of course is that one cannot view customer history through stripe however one could do this through our web app.

**Comment by leaguetek01** [comment]
was just going to post that indeed a new customer record is created for each transaction.
