### ISSUE TITLE
Improved Signup/Signin Flow

### ISSUE THREAD

**Issue by game7** [game7/sportified#104]
The current requirement to signup/signin prior to registration is a bit disjointed and disrupts the flow.  

* The signin screen does not provide equal/balanced exposure for both returning users and new users as it is heavily slanted towards "signin".  
* When creating a new account, the requirement to confirm that account via email is also high-friction.
* There is currently may be no protection from creating duplicate accounts.  Need to ensure uniqueness of email address and smooth handling when a duplicate account creation is attempted

**Comment by game7** [comment]
From a usability point of view it might be nice have user enter his/her email address first, after which we check for existence and route to either a signin or signup page.  Typically this approach is discouraged as it can provide a would-be hacker feedback that a particular email address exists within our system however one can actually accomplish the same by attempting to create a new account (in which case the system will provide the same feedback if the email already exists).  To safeguard against hacking we can activate the "lockable" feature of our user system which will lock a user account after *n* (configurable) failed login attempts with unlocking achieved by re-confirming the account via email.  I'd propose that accounts are locked after 10 attempts.

**Comment by leaguetek01** [comment]
Looks good. Works as expected
