### ISSUE TITLE
Punchlist for STYFL 

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#105]
- [x] Confirmation Page Text with confirmation/registration number
- [x]  Form Packet for Tackle
- [x] Form Packet for Flag
- [x] Build Registration page and Link to Registrar page
- [x] Clean up test data
- [x] Legal disclaimer agreement
- [x] Status management of registrations.
- [x] Prod keys
- [x] Add 3 registration items noted in comments
- [x] Diashboard (count of reg item by status)

**Comment by leaguetek01** [comment]
Legal Disclaimer Text for STYFL:
WAIVER AND RELEASE OF LIABILITY AND ASSUMPTION OF RISK AGREEMENT
I/We the parents of the STYFL Football player hereby give my/our approval to his/her participation in any and all activities associated with STYFL. I/We assume all risks and hazards incidental to such participation including transportation to and from the activities; and I/we hereby waive, release, absolve, indemnify and agree to hold harmless STYFL Football, the organizers, sponsors, supervisors, participants, coaches and any persons transporting my/our son/daughter. I acknowledge that I understand that participation in this program involves risk of serious injury and that while rules and protective equipment may reduce that risk, there is no way to eliminate the risk of serious injury. I acknowledge that if my child participates in a division consisting of older and/or heavier players; it is done by my sole direction and I assume any and all additional risks that such participation involves. Be it known that I/we, the parent or guardian of the player, do hereby give and grant unto any medical assistant, medical doctor or hospital my consent and authorization to render such aid, treatment or care to said player as in judgment of said medical assistant, doctor or hospital that may be required on an emergency basis in the event said player should be injured or stricken ill while participating in STYFL Football activities. I/We do hereby grant my/our permission to have said player photographed at league games and/or functions and release all rights to said photographs and authorize their use by STYFL Football and it’s affiliates for promotional purposes. I further accept full responsibility for all obligations, financial or other, which may result from injuries to my son/daughter while participating in the STYFL Football program. I also understand that STYFL Football does not provide accident insurance for my son/daughter. This waiver applies to myself, as well my heirs, devisees, assigns, personal representatives, guardians, conservators, administrators, agents, next of kin, and successors-in-interest.

**Comment by game7** [comment]
*converted to checklist*

**Comment by leaguetek01** [comment]
3 Reg items

Spring Flag Football - 2016
Spring Tackle Football - 2016
Spring Equipment Rental - 2016

**Comment by leaguetek01** [comment]
Prices

$90 - Spring Flag Football - 2016
$150 - Spring Tackle Football - 2016
$40 - Spring Equipment Rental - 2016
