### ISSUE TITLE
Sportified landing page points to oceanside

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#106]

**Comment by game7** [comment]
good catch - when a page is requested using an unknown hostname the system loads the first *Tenant* form the DB, which happens to be OIA.  Will need to setup a base Tenant for sportified and adjust this logic.

**Comment by game7** [comment]
This has been fixed.  Have setup new 'www' tenant with super basic theme.  Will need to circle back and add some content

![image](https://cloud.githubusercontent.com/assets/262805/21027535/69c66eae-bd4e-11e6-9724-1d7d16ffe8fd.png)
