### ISSUE TITLE
Form Elements for STYFL Spring 2017

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#110]
![image](https://cloud.githubusercontent.com/assets/8645743/21063563/70a299ee-be13-11e6-82d2-9d9abd322265.png)

**Comment by game7** [comment]
Forms are now setup for Tackle and Flag

![image](https://cloud.githubusercontent.com/assets/262805/21067349/e2d43fea-be27-11e6-801e-322babf45ab0.png)
