### ISSUE TITLE
Unresponsive screen on test payment

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#114]
![image](https://cloud.githubusercontent.com/assets/8645743/21162116/eee63e04-c148-11e6-95b6-e17796629e77.png)

**Comment by leaguetek01** [comment]
connect looks correct for prod
![image](https://cloud.githubusercontent.com/assets/8645743/21162152/1fcd9936-c149-11e6-8ecb-18525806d528.png)

**Comment by game7** [comment]
99.9% sure this was caused by the retention of test-provisioned customer_id number on user accounts after the cutover to production/live keys - thus closing 👊
