### ISSUE TITLE
Metadata to Stripe

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#115]
We send the reg ID in the metadata. Perhaps we include the conf number in case they need to process a refund. Having said that, perhaps we don't generate the conf number until after the Stripe transaction.

![image](https://cloud.githubusercontent.com/assets/8645743/21193774/a7c43cd6-c1ea-11e6-9594-970830d82b3b.png)

**Comment by game7** [comment]
The "locator" is generated upon the creation of the registration which is way before payment (and in some cases there may not be a payment).  For this reason I prefer not to think of it as a confirmation.  We can definitely send it over...  and we can probapy almost as easily trigger the refund from our side and keep the two systems in sync

**Comment by game7** [comment]
this should be landing in a few mintues (after build/deploy).  Let's assess what we are capturing now before deciding whether this issue can be closed

**Comment by game7** [comment]
coouuld be satisfied by #117... maybe?

**Comment by game7** [comment]
this one is a super-easy issue-close but requires a decision - what do we want?

**Comment by game7** [comment]
![image](https://cloud.githubusercontent.com/assets/262805/21274578/29850146-c386-11e6-9f1b-9f70fd8597e6.png)
