### ISSUE TITLE
Redirect Loop When Unauthorized User Requests an Admin Page

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#116]
Testing security on viewing registrations. Logged in as qa001 with no admin times out when trying to view all registrations. Good.

![image](https://cloud.githubusercontent.com/assets/8645743/21204408/7d67a106-c214-11e6-8517-860551adefca.png)

**Comment by game7** [comment]
Good and bad - seems to be stuck in a redirect loop which could mean that it's also hammering the server and possibly blocking/slowing other requests

**Comment by game7** [comment]
weird - I haven't been able to replicate that error screen that you've shared.  Perhaps it's because I'm logged out and in your case you are logged in as a non-admin user.  Will try that.

**Comment by game7** [comment]
ok - error reproduced.  should be fixable.
