### ISSUE TITLE
Punchlist for 3/1 STYFL registration

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#121]
- [x] Update fee to 4%
- [ ] Add 2017 Tackle - $175 (will increase on 4/15)
- [ ] Add 2017 Flag - $90
- [ ] Add 2017 Equipment - $40
- [x] Additions to Spring form for Tackle (secondary_contact_email, club_request, weight, years_experience, residency)
- [x] Additions to Spring form for Flag (secondary_contact_email, coach_request, residency)
- [x] Additions to Spring form for Equipment (birthdate)

Club request is radio button or drop down:
No Preference (default)
Blue Devils
Broncos
Bulldogs
Cardinals
Coyotes
Eagles
Special Forces
Sun Devils

Residency is radio button or drop down:
Queen Creek (default)
San Tan Valley
Gilbert
Mesa
Other

Years experience is 2 digit number

Weight is 3 digit number

**Comment by game7** [comment]
doable.

questions:

1. Club Request -- a list of actual "clubs" from league module?  or just a standalone form control that happens to have options that are aligned with the league module
2. Years Experience -- do you think a dropdown with a few ranges might be better?
3. Weight -- same as years - would a dropdown containing 5 lb increments be better?  Always more-difficult to validate open inputs than it is to restrict entry to options

**Comment by leaguetek01** [comment]
#1 sounds good, what about the No Preference?

I will run #2 and #3 by Adam this morning

**Comment by leaguetek01** [comment]
#2 use 0, 1-2, 3-4, 5+
#3 need to use 3 digit numeric.
