### ISSUE TITLE
Registration: Private Events

### ISSUE THREAD

**Issue by game7** [game7/sportified#185]
Require the ability to have an active registration that is not visible to the public

- [x] should be able to flag a product as private
- [x] should be open for registration if active
- [x] should not appear in public product pages
- [x] should not provide registration link in calendar
- [x] should not provide registration link in event feeds
- [x] should provide a link/url that can be easily copied and shared from admin screens

**Comment by OIATempe** [comment]
Our first "private" event will be on 6/10. I don't see the shareable link on the product page yet. What's status on that. Prob need to send out by Monday latest.

**Comment by game7** [comment]
that's a pretty easy add -- will see if I can get it up tomorrow morning.  Moving forward I'm thinking about also making variants have a private flag for situations where there is a public (or private) product where one particular variant/position is exclusive.  This could be very useful for goalies at open hockey
