### ISSUE TITLE
Office Person / Admin access

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#198]
Front Desk Person:
Dahsboard (For lockerroom assignmnets)
Registration / Attendance Checkin
Chromecast

Admin : 
Everything
[Employee_Directory Site Access.xlsx](https://github.com/game7/sportified/files/4788763/Employee_Directory.Site.Access.xlsx)

**Comment by OIATempe** [comment]
Also is there a way for this person to use passowrd (even if it is one we assign) so that they dont have to open their email first before loging into the site to perform tasks?

**Comment by game7** [comment]
related commits:
https://github.com/game7/sportified/commit/45995cdad89941081b7b45ed1e1cca8c5b95b84b
https://github.com/game7/sportified/commit/985717bfd951526a4529b6b018a6c0054ecab068
