### ISSUE TITLE
USA Hockey Numner

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#202]
Nine (9) Numbers Five (5) Letters:   123456789ABCDE
Fourth Digit can be either: 
   a zero (0) untill 8/31/20
   a one (1) untill 8/31/21

Needs to be collected from 
ARC/Skills Players
League Players

Need to be able to export list of numbers to be imported to USAHockey.com

**Comment by game7** [comment]
closed by https://github.com/game7/sportified/commit/7e70bf31586b5bb9f12413ee32bcdedeeb8c0004

added ability to do regex validation on text input
