### ISSUE TITLE
Saving check-ins

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#208]
Is there a way to have the system save who has been checked in for Adult items... Open Hockey, Skills. 

Currently you can check the box but once you leave the page all the check-marks go away,.

**Comment by game7** [comment]
ouch -- that was not the intent.  I think this is currently working as I was testing on it today... will take a look and fix if needed, otherwise we can probably close.

**Comment by game7** [comment]
re-confirmed that this feature would appear to be working fine 👍
