### ISSUE TITLE
Stripe order issue

### ISSUE THREAD

**Issue by OIATempe** [game7/sportified#210]
Look at registration under: CHEL D1/D2 Fall 2020
Player: Tim Hoffenkamp
Issue: Started transaction on Wednesday. Adam Canceled Transaction on Thursday (Abandoned) 
Look at Payment status link, Payment started on the 2nd @ 7p. Completed on the 3rd @1045a. 

For this player we need to go back and mark him as complete. 
 is it possible this might come up again, if yes can we make a way for us to make this switch  (from abandoned to complete)

**Comment by game7** [comment]
I can go in and manually "un-abandon" the order.  was this accidentally marked as abandoned?  It looks like it was previously in 'completed' status

**Comment by game7** [comment]
I think this was for a specific registration and that there currently are no system changes to be made.  If I'm mistaken we can reopen as needed
