### ISSUE TITLE
IGnore in standings flag broken in standings

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#61]

**Comment by leaguetek01** [comment]
Was this fixed already? Still see the same issue.

**Comment by game7** [comment]
Should have been fixed by 673d870750bd7890b8e33f5815af5bce79a547d3 - you can see that the query was updated to include only teams where `show_in_standings: true`.  I also performed both positive and negative testing prior to releasing.  Is there a specific context or example that I can look at?

**Comment by game7** [comment]
I'm pretty sure this is related to data conversion and thus no code changes required.  @leaguetek01 mentioned that number of impacted games is pretty small and thus should be able to be manually-corrected.  Closing issue for now and can reopen if a programmatic solution is required.
