### ISSUE TITLE
Menu links in styfl

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#62]

**Comment by leaguetek01** [comment]
Updated from /program/ to /league/STYFL/

**Comment by game7** [comment]
Were these custom-defined links that were broken by the URL changes?  I just realized we may have a few of these on oceanside site

**Comment by leaguetek01** [comment]
They were the links from the menu. I updated via the edit function in admin>pages. You had already update the quick links that were on the landing page.

**Comment by game7** [comment]
At some point I'd like to make both quick links and menu "pointers" so that we don't have static irks.  Would also make it easier for administrators to setup.
