### ISSUE TITLE
Image blocks do not allow edit selection. 

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#63]

**Comment by game7** [comment]
Looks like something is broken with the ability to provide a url to a remote file

![image](https://cloud.githubusercontent.com/assets/262805/15402425/01404246-1da9-11e6-96c6-545f30a827b9.png)

**Comment by game7** [comment]
duh - should be remote_file_url

![image](https://cloud.githubusercontent.com/assets/262805/15402715/7bfda16c-1daa-11e6-96a7-a772decc0cfb.png)
