### ISSUE TITLE
RMS: Form Elements

### ISSUE THREAD

**Issue by leaguetek01** [game7/sportified#89]
Generic, reusable form elements

- [x] Text: Basic Text Input
- [x] Email: Text Input that validates email format
- [x] Phone: Text input that validates phone format
- [x] Note: Multiline Text Input
- [ ] Number: Text input with validation for number format
- [x] Name: Composite element with text input for first and last name
- [x] Address: Composite elements with all address fields (street, city, state, postal)
- [ ] Checkbox: 
- [x] Options: select from a list of options.  system decides to render as dropdown or radio based on number of options
- [x] Height: Composite element with inputs for feet and inches
- [ ] Weight: numeric input with validation for reasonable weight range
- [x] Contact:  a composite element comprised of first name, last name, email and phone number
- [x] Legal: a composite element comprised of multi-line, readonly textarea containing terms and conditions as well as a checkbox for user to indicate that he/she accepts them

*checked elements have been implemented*

**Comment by game7** [comment]
Elements need to be broken down into generic, reusable equivalents:

| Element           | Form Field Type | Notes             |
| ---------         | ---------       | ----              |
| CreatedOn         | n/a             | Standard          |
| Activity          | n/a             | Standard          |
| Title             | n/a             | Standard          |
| StatusName        | n/a             | Standard (TBD)    |
| PaymentStatusName | n/a             | Standard (TBD)    |
| PlayerLastName    | Name            |                   |
| PlayerFirstName   | Name            |                   |
| CertWeight        | TBD             |                   |
| PlayerBirthdate   | Date            |                   |
| LeagueAge         | Number          |                   |
| CustomerLastName  | Name            |                   |
| CustomerFirstName | Name            |                   |
| PrimaryPhone      | Phone           |                   |
| PrimaryEmail      | Email           |                   |
| SecondaryPhone    | Phone           |                   |
| SecondaryEmail    | Email           |                   |
| Address1          | Address         |                   |
| Address2          | Address         |                   |
| City              | Address         |                   |
| State             | Address         |                   |
| Zip               | Address         |                   |
| InsuranceCarrier  | Text            |                   |
| InsurancePolicy   | Text            |                   |
| Allergies         | Note            |                   |
| ReturningPlayer   | Checkbox        |                   |
| ClubAssigned      |                 |                   |
| ClubRequest       |                 |                   |
| Height            | Height          |                   |
| Weight            | Weight          |                   |
| Experience        | Number          |                   |
| Referral          | Note            |                   |
| Comments          | Note            |                   |
| Waiver            |                 |                   |
| CoachRequest      | Text            |                   |
| Age               | Number          |                   |
| Jersey            | Options         | Dropdown or Radio |

**Comment by game7** [comment]
Forms are structured as such:

* A **Form Packet** *has one or more* **Form Templates** *having one or more* **Form Fields**
* Each **Variant** for a registrable **Item** may be assigned a Form Packet
* Upon registration, the newly created **Registration** shall be initialized with an empty **Form** for each Form Template that belongs to the associated Form Packet
* During **Checkout**, the user shall be stepped through each form before finally landing on the payment screen.  Upon successful payment the user is taken to the confirmation screen

Models:

* [Form Packet](https://github.com/game7/sportified/blob/master/engines/rms/app/models/rms/form_packet.rb)
* [Form Template](https://github.com/game7/sportified/blob/master/engines/rms/app/models/rms/form_template.rb)
* [Form Field](https://github.com/game7/sportified/blob/master/engines/rms/app/models/rms/form_field.rb)
* [Form](https://github.com/game7/sportified/blob/master/engines/rms/app/models/rms/form.rb)

**Comment by game7** [comment]
Added "Legal" form control to checklist per requirement in #105

**Comment by game7** [comment]
Implementation of "Agreement" form control - formerly referred to as "Legal" per #105 

![image](https://cloud.githubusercontent.com/assets/262805/20955476/babd2fae-bc00-11e6-96e9-ac4ea753c1de.png)

**Comment by game7** [comment]
I think we have sufficient form elements to close this issue as #110 has been satisfied
