### ISSUE TITLE
Registration: Test Scenarios

### ISSUE THREAD

**Issue by game7** [game7/sportified#90]
TODO: add checklist of end-to-end test scenarios. be sure to include

* user signup vs. user signin
* various credit card exceptions
* user trying forward/backward navigation during checkout
* user trying multiple subsequent registrations

**Comment by leaguetek01** [comment]
![image](https://cloud.githubusercontent.com/assets/8645743/20821698/edaeff30-b801-11e6-8597-fe1650c6cbf7.png)

**Comment by leaguetek01** [comment]
![image](https://cloud.githubusercontent.com/assets/8645743/20821706/02273a90-b802-11e6-833b-93b711bba504.png)

**Comment by leaguetek01** [comment]
![image](https://cloud.githubusercontent.com/assets/8645743/20821715/10bce640-b802-11e6-8c14-168a03685270.png)

**Comment by leaguetek01** [comment]
If new card is selected and same card is used, we reflect 2 cards with the same number.

**Comment by leaguetek01** [comment]
If no card is selected, a blank screen is returned. Navigating back allows correction.

**Comment by leaguetek01** [comment]
All card types work with the exception of Diners

**Comment by game7** [comment]
ping! - do we have any opens on this one?

**Comment by leaguetek01** [comment]
I have a test scenario sheet that I started. Needs some work so I will track it here.
