### ISSUE TITLE
RMS: Confirmation Screen

### ISSUE THREAD

**Issue by game7** [game7/sportified#95]
Need to come up with a design for this confirmation screen that is displayed following a successful registration.  Most of the elements on this screen should be of a universal design while there may be some things that may be configured per client and/or product.

![image](https://cloud.githubusercontent.com/assets/262805/20690064/beb538f8-b585-11e6-8615-d4b72ab4d1af.png)

**Comment by leaguetek01** [comment]
should be very similar to the email confirmation IMO

**Comment by game7** [comment]
![image](https://cloud.githubusercontent.com/assets/262805/21020784/0d9e1e08-bd33-11e6-9a59-d45bb3a2d6ce.png)
