### ISSUE TITLE
RMS: Confirmation Email

### ISSUE THREAD

**Issue by game7** [game7/sportified#96]
We currently aren't sending anything... but we probably should.  

@leaguetek01 Is there anything we can borrow from leaguetek to serve as a starting point?

**Comment by leaguetek01** [comment]
Very basic on screen confirmation on LT:

<p>Thank you for enrolling your player in this San Tan Youth Football League activity.</p>
<p><b>Please print this enrollment confirmation for your records. <br>Watch the website and your email for information on certifications, equipment hand-out, and next steps.</b></p>

**Comment by leaguetek01** [comment]
In general, we want the email to be simple and re-usable without needing to worry about changing it season for season or by activity.

**Comment by game7** [comment]
Didn't realize it was this simple... but even so, the content is specific to the client STYFL.  I think to be quick and simple we can hard-code this into the mail this week and then circle back later and make it something that is configurable.

**Comment by game7** [comment]
basic confirmation email is up and running... and ready to adjust wording as needed.

![image](https://cloud.githubusercontent.com/assets/262805/20698105/dc658ea8-b5bb-11e6-9905-4ebcf2d96952.png)

**Comment by game7** [comment]
![image](https://cloud.githubusercontent.com/assets/262805/21021118/6c8f46a2-bd34-11e6-86f3-496572bb9821.png)
