### ISSUE TITLE
RMS: Registration Detail

### ISSUE THREAD

**Issue by game7** [game7/sportified#99]
Need to determine minimum viable design for registration detail page -- both for customers and administrators

![image](https://cloud.githubusercontent.com/assets/262805/20690272/c1ffe494-b586-11e6-9933-69cb3c07dce0.png)

**Comment by leaguetek01** [comment]
Single page or multiple for reg data. Payment page is seperate page I presume

**Comment by game7** [comment]
This page is to view the registration information after-the-fact.  During the actual registration and/or checkout, it is beneficial to walk the user page-by-page so that we can keep focus on different groups of information and also cater to smaller screens... but in this case it will be the admin who is looking at completed registrations so it may not be necessary to be as granular as checkout. 

 I think the objective should be to make the information presentable and easy to find so that the primary scenario is to view the information online rather than dump it all to excel.  Dump to excel is still a capability that we should and will provide, but I don't think it should be the default -- I think the system should make it very easy to locate a registration or customer and view the forms online... and initiate communication via email, phone or SMS for one or many registrations.
